import { Link } from 'react-router-dom'
import { WEIGHTS } from '../utils/scoring'

export default function Methodology() {
  return (
    <>
      <section className="pagehead">
        <div className="container">
          <div className="eyebrow" style={{ color: '#6db6ff' }}>
            Transparency
          </div>
          <h1>How we rank companies</h1>
          <p>
            Rankings on VietnamITOutsourcing are generated by the VITO Score — a transparent,
            weighted formula. No company can pay to rank higher.
          </p>
        </div>
      </section>

      <section className="section">
        <div className="container" style={{ maxWidth: 860 }}>
          <div className="panel prose">
            <h3>The VITO Score</h3>
            <p>
              Every company receives a single 0–100 score that blends six weighted components. The
              formula deliberately rewards <strong>client-reported satisfaction, value and quality</strong>{' '}
              over raw company size — so a highly-rated specialist can out-rank a much larger firm.
              Headcount and review volume are log-scaled to prevent enterprise giants from
              automatically dominating.
            </p>

            <div className="compare-wrap" style={{ marginTop: 18 }}>
              <table className="formula-table">
                <thead>
                  <tr>
                    <th>Component</th>
                    <th>Weight</th>
                    <th>What it measures</th>
                  </tr>
                </thead>
                <tbody>
                  {WEIGHTS.map((w) => (
                    <tr key={w.key}>
                      <td style={{ fontWeight: 600 }}>{w.label}</td>
                      <td className="w">{Math.round(w.weight * 100)}%</td>
                      <td>{DESCRIPTIONS[w.key]}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          <div className="panel prose">
            <h3>Our data sources</h3>
            <ul className="list-plain">
              <li>Publicly reported company information (founding year, HQ, headcount, offices)</li>
              <li>Aggregated verified client reviews across major B2B directories</li>
              <li>Public certifications and industry awards</li>
              <li>Delivery sub-scores for quality, schedule, cost and communication</li>
            </ul>
            <p style={{ marginTop: 14 }}>
              We re-calculate rankings quarterly and update profiles as new information becomes
              available.
            </p>
          </div>

          <div className="panel prose">
            <h3>Editorial independence</h3>
            <p>
              VietnamITOutsourcing does not sell ranking positions. Sponsored placements, when
              present, are always clearly labelled and never affect a company’s VITO Score.
            </p>
          </div>

          <div style={{ textAlign: 'center', marginTop: 12 }}>
            <Link to="/directory" className="btn btn-primary">
              Explore the ranked directory →
            </Link>
          </div>
        </div>
      </section>
    </>
  )
}

const DESCRIPTIONS = {
  rating: 'Average overall client rating (0–5) normalized to a 100-point scale.',
  delivery: 'Combined quality, on-time delivery, value-for-cost and communication sub-scores.',
  retention: 'Share of clients who continue or renew engagements — a proxy for trust.',
  credentials: 'Recognized certifications (ISO, CMMI) and industry awards.',
  reviews: 'Volume of verified reviews, log-scaled so a few great reviews still count.',
  scale: 'Delivery capacity based on engineering headcount, log-scaled.',
}
