import { Link } from 'react-router-dom'

export default function Footer() {
  const year = 2026
  return (
    <footer className="footer">
      <div className="container">
        <div className="footer-grid">
          <div>
            <div className="brand" style={{ color: '#fff', marginBottom: 12 }}>
              <span className="flag">★</span>
              <span>
                Vietnam<b style={{ color: '#6db6ff' }}>IT</b>Outsourcing
              </span>
            </div>
            <p style={{ fontSize: 14, maxWidth: 320, color: '#aab4cc' }}>
              The independent directory and rankings of Vietnam’s leading IT
              outsourcing and software development companies. Built to help
              global clients shortlist the right partner with confidence.
            </p>
          </div>

          <div>
            <h5>Explore</h5>
            <Link to="/directory">All companies</Link>
            <Link to="/directory?sort=rating">Top rated</Link>
            <Link to="/compare">Compare firms</Link>
            <Link to="/methodology">How we rank</Link>
          </div>

          <div>
            <h5>Services</h5>
            <Link to="/directory?service=Custom%20Software%20Development">Custom software</Link>
            <Link to="/directory?service=Staff%20Augmentation%20%2F%20Dedicated%20Teams">Dedicated teams</Link>
            <Link to="/directory?service=Mobile%20App%20Development">Mobile apps</Link>
            <Link to="/directory?service=AI%20%26%20Machine%20Learning">AI &amp; ML</Link>
          </div>

          <div>
            <h5>Locations</h5>
            <Link to="/directory?city=Ho%20Chi%20Minh%20City">Ho Chi Minh City</Link>
            <Link to="/directory?city=Hanoi">Hanoi</Link>
            <Link to="/directory?city=Da%20Nang">Da Nang</Link>
          </div>
        </div>

        <div className="disclaimer">
          <strong>Disclaimer:</strong> VietnamITOutsourcing is a demo product. Company profiles
          combine publicly reported information with illustrative demo data (ratings, review
          counts, sub-scores and pricing bands). Rankings are generated by our published{' '}
          <Link to="/methodology" style={{ color: '#9fd0ff' }}>VITO Score methodology</Link> and
          do not constitute an endorsement. Always conduct your own due diligence before selecting
          a vendor.
        </div>

        <div className="footer-bottom">
          <span>© {year} VietnamITOutsourcing. All rights reserved.</span>
          <span>Made for the global tech community · Built with React, deployed on Vercel</span>
        </div>
      </div>
    </footer>
  )
}
